{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Movies\",\"People\",\"MoviesCast\",\"GenreRank\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "16613a74-c74b-4464-8dab-6cdc34bc9b4d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Title Id",
        "fromTable": "MoviesCast",
        "toColumn": "Title Id",
        "toTable": "Movies"
      },
      {
        "name": "5f6fb4c4-b3ca-4c95-875f-05177994c5cf",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Person Name Id",
        "fromTable": "MoviesCast",
        "toColumn": "Person Name Id",
        "toTable": "People"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Movies",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd696e10-8572-40e4-a9c1-772c26b66d39",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25b7d1f1-3e5e-4c9b-9dea-b79e8ebb3e71",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf6eee7e-bea7-4fa3-bed5-7a5c15ff7561",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Language",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c97468ca-42ab-4e6e-b478-05703e00f1a6",
            "sourceColumn": "Language",
            "summarizeBy": "none"
          },
          {
            "name": "Plot",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10255f17-bcaf-4785-bd35-02cb67683c18",
            "sourceColumn": "Plot",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8166f43a-c0e5-4891-9a30-2fa152ff7d09",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Tagline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3494a69e-0603-4856-ab4e-0994ee4f0cb0",
            "sourceColumn": "Tagline",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02b2476c-d746-4f0d-9746-b0493d33ddce",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Title Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6977ec08-716f-4874-aecf-4e5f1308204f",
            "sourceColumn": "Title Id",
            "summarizeBy": "none"
          },
          {
            "name": "Number Of Votes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f85e1f25-14db-466e-a139-2eb87318b144",
            "sourceColumn": "Number Of Votes",
            "summarizeBy": "sum"
          },
          {
            "name": "Best Picture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fddbfd2-f477-489c-a8c5-94fd02a20d03",
            "sourceColumn": "Best Picture",
            "summarizeBy": "none"
          },
          {
            "name": "Certificate Gb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17ba95b3-772e-48e8-a95e-d6c0f7acb266",
            "sourceColumn": "Certificate Gb",
            "summarizeBy": "none"
          },
          {
            "name": "Certificate Us",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53aed9b2-16c4-4255-bb34-3bef0a1ee942",
            "sourceColumn": "Certificate Us",
            "summarizeBy": "none"
          },
          {
            "name": "Contains Genre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c2e71c90-0bbf-467f-8ce6-5747272104f1",
            "sourceColumn": "Contains Genre",
            "summarizeBy": "none"
          },
          {
            "name": "Contains Production Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c3213d2d-984f-48b4-99df-66264090efdc",
            "sourceColumn": "Contains Production Company",
            "summarizeBy": "none"
          },
          {
            "name": "Genres 1St",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "747aa3ad-47c0-47eb-8643-1f58ec9fa40c",
            "sourceColumn": "Genres 1St",
            "summarizeBy": "none"
          },
          {
            "name": "Genres 2Nd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f84e638-6d5e-4fa4-8d57-f9e29b184e62",
            "sourceColumn": "Genres 2Nd",
            "summarizeBy": "none"
          },
          {
            "name": "Genres 3Rd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bcd2f3c-ba62-476f-b77e-77c00b51f4b0",
            "sourceColumn": "Genres 3Rd",
            "summarizeBy": "none"
          },
          {
            "name": "Genres Full List",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "976d9116-d4f3-4088-8342-276c68f462b7",
            "sourceColumn": "Genres Full List",
            "summarizeBy": "none"
          },
          {
            "name": "Image Url Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbde671b-53c1-46c1-9395-049154c57300",
            "sourceColumn": "Image Url Title",
            "summarizeBy": "none"
          },
          {
            "name": "Imdb Url Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e29463e-8989-4098-a8b0-d583e4a4af04",
            "sourceColumn": "Imdb Url Title",
            "summarizeBy": "none"
          },
          {
            "name": "Plot Medium",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14b39d65-ea62-4c96-8c69-67390f192e12",
            "sourceColumn": "Plot Medium",
            "summarizeBy": "none"
          },
          {
            "name": "Production Companies 1St",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4314708-9e18-4a0a-a5de-d7341ece8d28",
            "sourceColumn": "Production Companies 1St",
            "summarizeBy": "none"
          },
          {
            "name": "Production Companies 2Nd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cc2be15-b254-4ed3-8228-227b5ae189d7",
            "sourceColumn": "Production Companies 2Nd",
            "summarizeBy": "none"
          },
          {
            "name": "Production Companies 3Rd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93e21cdd-36fb-459a-a845-95ebb2c21bd5",
            "sourceColumn": "Production Companies 3Rd",
            "summarizeBy": "none"
          },
          {
            "name": "Production Companies List",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "425a55f7-9ae4-4de4-8c72-830ec8488fc5",
            "sourceColumn": "Production Companies List",
            "summarizeBy": "none"
          },
          {
            "name": "Year Of Release",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c3f84179-2d24-4c32-ac31-599cf916781d",
            "sourceColumn": "Year Of Release",
            "summarizeBy": "none"
          },
          {
            "name": "Imdb Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b41eebb6-f7bc-428c-ade7-e3906c7d2c68",
            "sourceColumn": "Imdb Rating",
            "summarizeBy": "average"
          },
          {
            "name": "Number Of Titles",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6afbb0f4-a1ed-481d-94b9-0c42052ac096",
            "sourceColumn": "Number Of Titles",
            "summarizeBy": "sum"
          },
          {
            "name": "Runtime Minutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41ee7497-2137-4ab7-90ef-415321d0f8f8",
            "sourceColumn": "Runtime Minutes",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7ed2b768-ca84-4ee2-a3dd-16fd1f128194",
        "partitions": [
          {
            "name": "Movies",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=\"petsathome-datawarehouse-test\"]){[Name=\"petsathome-datawarehouse-test\"]}[Data], \"SELECT * FROM `petsathome-datawarehouse-test`.datawarehouse_sample.imdb_movies#(lf)WHERE year_of_release>=2020\", null, [EnableFolding=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"number_of_votes\", Int64.Type}, {\"runtime_minutes\", Int64.Type}}),",
                "   Custom1 = Table.TransformColumnNames( #\"Changed Type\",  each Text.Proper(Text.Replace( _, \"_\", \" \" )) )",
                "in",
                "    Custom1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "People",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Person Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0ce9fab-c6d8-4c48-b6ec-87a758925296",
            "sourceColumn": "Person Name",
            "summarizeBy": "none"
          },
          {
            "name": "Person Name Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6027ab58-b9e9-4eb8-bb5a-d5db49416887",
            "sourceColumn": "Person Name Id",
            "summarizeBy": "none"
          },
          {
            "name": "Imdb Url Person",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a42c4b9e-6629-43f2-be56-285c6ec56f67",
            "sourceColumn": "Imdb Url Person",
            "summarizeBy": "none"
          },
          {
            "name": "Number Of People",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8272f170-a71f-498d-a8ab-c5ee48e85c2e",
            "sourceColumn": "Number Of People",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1faf77bf-897b-4ae4-9944-fc7beb67a9af",
        "partitions": [
          {
            "name": "People",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=\"petsathome-datawarehouse-test\"]){[Name=\"petsathome-datawarehouse-test\"]}[Data], \"SELECT * FROM `petsathome-datawarehouse-test`.datawarehouse_sample.imdb_people p#(lf)WHERE EXISTS (SELECT 1 FROM `petsathome-datawarehouse-test`.datawarehouse_sample.imdb_movies m#(lf) INNER JOIN `petsathome-datawarehouse-test`.datawarehouse_sample.imdb_movies_cast mc ON m.title_id=mc.title_id#(lf)WHERE year_of_release>=2020#(lf)AND p.person_name_id=mc.person_name_id#(lf))\", null, [EnableFolding=true]),",
                "    Custom1 = Table.TransformColumnNames( Source,  each Text.Proper(Text.Replace( _, \"_\", \" \" )) )",
                "in",
                "    Custom1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MoviesCast",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Title Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f5b3f13-c360-41a2-8c6d-23ed075572b7",
            "sourceColumn": "Title Id",
            "summarizeBy": "none"
          },
          {
            "name": "Person Name Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2b94861-5b05-4a1e-abd7-b619e5011200",
            "sourceColumn": "Person Name Id",
            "summarizeBy": "none"
          },
          {
            "name": "What Did They Do",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b79375ab-a4eb-4e1b-92c0-fff9d0bdaa36",
            "sourceColumn": "What Did They Do",
            "summarizeBy": "none"
          },
          {
            "name": "Who Did They Play",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d698a61-63f0-4060-8fb8-5c1177ff772d",
            "sourceColumn": "Who Did They Play",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Position In Cast List",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ecec63ba-a186-4e6d-ad86-685ebbab885e",
            "sourceColumn": "Billing Position In Cast List",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "72db31ca-06b1-463a-ac69-3d3ffc361b98",
        "partitions": [
          {
            "name": "MoviesCast",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=\"petsathome-datawarehouse-test\"]){[Name=\"petsathome-datawarehouse-test\"]}[Data], \"SELECT * FROM `petsathome-datawarehouse-test`.datawarehouse_sample.imdb_movies_cast mc#(lf)WHERE EXISTS (SELECT 1 FROM `petsathome-datawarehouse-test`.datawarehouse_sample.imdb_movies m#(lf)WHERE year_of_release>=2020 AND m.title_id=mc.title_id)\", null, [EnableFolding=true]),",
                "    Custom1 = Table.TransformColumnNames( Source,  each Text.Proper(Text.Replace( _, \"_\", \" \" )) )",
                "in",
                "    Custom1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GenreRank",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f5c4e93a-03f5-4277-b08d-4e26d3f43701",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          },
          {
            "name": "Genres 1St",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3ad1b04-8298-4795-ae93-778ada7f631b",
            "sourceColumn": "Genres 1St",
            "summarizeBy": "none"
          },
          {
            "name": "Movies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1aafdf91-0583-457c-9920-d6fd2eaf0a53",
            "sourceColumn": "Movies",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3f2b9341-54bc-41b2-97f3-4ca8d2e459fe",
        "measures": [
          {
            "name": "Tom Cruise Films",
            "expression": "CALCULATE(COUNTROWS(Movies),FILTER (People,People[Person Name]=\"Tom Cruise\"))",
            "formatString": "0",
            "lineageTag": "8c4edd8d-365e-4dc8-89b0-bcdcb060f88c"
          },
          {
            "name": "Cate Blanchett Films",
            "expression": "CALCULATE(COUNTROWS(Movies),FILTER (People,People[Person Name]=\"Cate Blanchett\"))",
            "formatString": "0",
            "lineageTag": "63ac4b33-da27-4ef9-8c25-badb60896df5"
          }
        ],
        "partitions": [
          {
            "name": "GenreRank",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "   Source = Value.NativeQuery(GoogleBigQuery.Database([BillingProject=\"petsathome-datawarehouse-test\"]){[Name=\"petsathome-datawarehouse-test\"]}[Data], \"WITH movie_data AS (#(lf)SELECT genres_1st, COUNT(*) movies#(lf)FROM  `petsathome-datawarehouse-test`.datawarehouse_sample.imdb_movies#(lf)WHERE year_of_release>=2020#(lf)GROUP BY 1)#(lf)SELECT  genres_1st,#(lf)        movies,#(lf)        CASE WHEN genres_1st IS NOT NULL THEN ROW_NUMBER() OVER (order by movies DESC) ELSE 100 END AS Index#(lf)FROM movie_data\", null, [EnableFolding=true]),",
                "    Custom1 = Table.TransformColumnNames( Source,  each Text.Proper(Text.Replace( _, \"_\", \" \" )) )",
                "in",
                "    Custom1"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}